services:
  openeo_odc_driver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    ports:
      - 5001:5000
    volumes:
      - /mnt/CEPH_OPENEO/data/odc-driver/:/data/odc-driver/
      - /mnt/CEPH_OPENEO/logs/odc-driver/:/logs/odc-driver/
    restart: always
    healthcheck:
      test: wget --no-check-certificate --no-verbose --tries=1 --spider http://localhost:5001/collections || exit 1
      interval: 120s
      retries: 5
      start_period: 60s
      timeout: 10s
